apiVersion: v1
kind: Pod
metadata:
  name: nginx5
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: quay.io/gauravkumar9130/nginxdemo
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disk: ssd
