apiVersion: v1
kind: Pod
metadata:
  name: envar-plain
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: mysql
    image: quay.io/gauravkumar9130/mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "redhat"
