apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: quay.io/gauravkumar9130/nginxdemo
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "cpu"
    operator: "Exists"
    effect: "NoExecute"
