apiVersion: v1
kind: Pod
metadata:
  name: volcm-pod
spec:
  containers:
    - name: nginx
      image: quay.io/gauravkumar9130/nginxdemo
      volumeMounts:
      - name: config-volume
        mountPath: /data
  volumes:
    - name: config-volume
      configMap:
        name: mysql-vol
